branches:
  only:
    - master

image: Visual Studio 2017

version: 0.0.0.{build}
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  GITHUB_ACCESS_TOKEN:
    secure: Cdow6TvcKRyrgFtLTKJIK8RcgbKyurMR4XxNaDc6Wal8Bufo+tIrwktoste0Ziof

build_script:
  - appveyor.cmd

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

artifacts:
  - path: 'build\**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: QLCKYXCwKUJVsVq5jP9h1Brvqgr41vxdN9fNzhIKiMM0FFi38JdDA9KvUGsBWZmF

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "rob@robmensching.com"
  - git config --global user.name "Rob Mensching"
  - git tag v%APPVEYOR_BUILD_VERSION%
  - git push --tags origin HEAD:master

notifications:
  - provider: Email
    to:
    - rob@robmensching.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
